# fly.toml file generated for tabia-bot on 2022-09-05T15:09:09+03:00

app = "tabia-bot"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"
